apiVersion: v1
kind: Pod
metadata:
  name: __INIT_POD_NAME__
spec:
  nodeSelector:
    env: dev
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: work
      mountPath: /work
    - name: nginxconf
      mountPath: /nginxconf
  volumes:
  - name: work
    persistentVolumeClaim:
        claimName: __PROJECT__-work
  - name: nginxconf
    persistentVolumeClaim:
        claimName: __GROUP_NAME__-nginx-conf
